 
 "use client"
 import './globals.css'
import { Inter } from 'next/font/google'
  
import 'bootstrap/dist/css/bootstrap.min.css';
import Providerr from '@/redux/Provider';
  import Navbar from '@/Component/Navbar';
import Cart from '../../Component/Cart';
  // import SuccessPage from './StripeSuccess/page';
    
 
      
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
   
         <Providerr    >  
         <Navbar/>    
     <Cart/>
          {/* <SuccessPage />    */}
     
          {children}
        
         </Providerr >
        
        
        
       </body>

    </html>
  )
}
